homeassistant:
  # Name of the location where Home Assistant is running
  name: Maison
  # Location required to calculate the time the sun rises and sets
  latitude: !secret latitude_home
  longitude: !secret longitude_home
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: !secret elevation_home
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Paris
  # Customization file
  customize: !include customize.yaml
###################################################
#                                                 #
#                   IFTTT                         #
#                                                 #
###################################################

ifttt:
  key: !secret ifttt_key

# Show links to resources in log and frontend
#introduction:

# Enables the frontend
frontend:

# Enables configuration UI
config:

http:
  # Secrets are defined in the file secrets.yaml
  api_password: !secret http_password
  # Uncomment this if you are using SSL/TLS, running in Docker container, etc.
  base_url: !secret base_url
  ssl_certificate: !secret ssl_certificate
  ssl_key: !secret ssl_key  
  #server_port: 80
  ip_ban_enabled: False #True
  login_attempts_threshold: 3
  trusted_networks:
    - 192.168.0.10
    - 192.168.0.14
    - 192.168.0.17


# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  include_used_components: true

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

#panel_iframe:
#  configurator:
#    title: Configurator
#    icon: mdi:wrench
#    url: https://192.168.0.20:3218

# Enables support for tracking state changes over time
history:
  exclude:
    entities:
      - sensor.moon
      - sensor.last_boot
    domains:
      - weblink
      #- zone
      - automations
      - updater

# View all events in a logbook
logbook:
  exclude:
    entities:
      - sensor.date
      - sensor.time
      - sensor.time_utc
      - sensor.time__date
      - sensor.load_5m
      - sensor.date__time
    domains:
      - weblink
      - group

recorder:
  #purge_interval: 2
  purge_keep_days: 30
  db_url: !secret mariadb_connection_url
  exclude:
    entities:
      #- sun.sun
      - sensor.moon
      - sensor.last_boot
      #- sensor.date
    domains:
      #- media_player
      #- scene
      - weblink
      #- zone
      #- plant
      #- input_number
      - automations
      - updater

# Enables a map showing the location of tracked devices
map:

# Track the sun
sun:

# Text to speech
tts:
  - platform: google

# Cloud
#cloud:

# twilio
twilio:
  account_sid: !secret twilio_account
  auth_token: !secret twilio_token

# Notify
notify:
  - name: pushbullet
    platform: pushbullet
    api_key: !secret pushbullet_key
  - name: anthony_sms
    platform: twilio_sms
    from_number: !secret twilio_number
  - name: anthony_messenger
    platform: facebook
    page_access_token: !secret facebook_token

# Include configuration files
group: !include groups.yaml
automation: !include_dir_merge_list automations
input_boolean: !include input_boolean.yaml
input_number: !include input_number.yaml
#plant: !include plants.yaml
script: !include_dir_merge_named scripts
sensor: !include sensors.yaml
device_tracker: !include device_tracker.yaml
weblink: !include weblink.yaml
zone: !include zones.yaml
scene: !include_dir_merge_list scenes
shell_command: !include shell_commands.yaml
switch: !include switches.yaml

#################
# Xiaomi Gateway
xiaomi_aqara:
  discovery_retry: 5
  gateways:
    - key: !secret xiaomy_gw_key

###############
# Yeelight
light:
  - platform: yeelight
    devices:
      192.168.0.40:
        #name: Door lamp
        name: child lamp
        use_music_mode: False #True
        save_on_change: False
        transition: 100
      192.168.0.41:
        name: Bedroom lamp
        use_music_mode: False #True
        save_on_change: False
        transition: 100
      192.168.0.42:
        name: kitchen lamp
        use_music_mode: False #True
        save_on_change: False
        transition: 100
      # avant: 192.168.0.42:
      192.168.0.43:
        name: corridor lamp
        use_music_mode: False #True
        save_on_change: False
        transition: 100
      # living room avant : 192.168.0.43
      192.168.0.44:
        name: living lamp
        use_music_mode: False #True
        save_on_change: False
        transition: 100

#mqtt:
#  broker: 192.168.0.20
#  port: 1883
#  client_id: !secret mqtt_client_id
#  keepalive: 60
#  username: !secret mqtt_user 
#  password: !secret mqtt_pass

media_player:
  - platform: kodi
    host: 192.168.0.20
 
  - platform: mpd
    host: 192.168.0.20
    name: mopidy

google_assistant:
  project_id: !secret google_project_id
  client_id: !secret google_client_id
  access_token: !secret google_access_token
  agent_user_id: !secret google_agent_user_id
  #api_key: !secret google_project_api_key
  exposed_domains:
    - switch
    - light
    - media_player
    - group

vacuum:
  - platform: xiaomi_miio
    host: 192.168.0.50
    token: !secret xiaomi_vacuum

#hdmi_cec:
#  devices:
#    TV: 0.0.0.0
#    Freebox player: 2.0.0.0

# TODO
# https://community.home-assistant.io/t/alarmsystem-with-appdaemon/31312/4

