- platform: yr
  monitored_conditions:
    - temperature
    - symbol
    - precipitation
    - humidity
    - cloudiness

# Moon
- platform: moon

# Weather
- platform: wunderground
  api_key: !secret wu_api_key
  lang: FR
  monitored_conditions:
    - alerts
    - location
    - temp_c
    - weather
    - feelslike_string
    - precip_1hr_metric
    - wind_kph
# SSL certificate expiration
- platform: cert_expiry
  host: !secret hass_url
  port: !secret ssl_port
# For Alarm Clock
- platform: template
  sensors:
    alarm_time:
      friendly_name: 'Heure'
      value_template: '{{ "%0.02d:%0.02d" | format(states("input_number.alarmhour") | int, states("input_number.alarmminutes") | int) }}'

- platform: time_date
  display_options:
    - 'time'
    - 'date'
    - 'date_time'
    - 'time_date'
    - 'time_utc'

# xiaomi Mi Flora
- platform: miflora
  mac: !secret mac_miflora1
  name: Fleur de Lune
  monitored_conditions:
    - temperature
    - moisture
    - light
    - battery
    - conductivity

# Gearbest
- platform: gearbest
  currency: EUR
  items:
    - id: 626695
      name: Xiaomi Aqara Switch
    - id: 626702
      name: Xiaomi Aqara Temp Sensor
    - id: 659226
      name: Xiaomi Aqara Motion Sensor
    - id: 626703
      name: Xiaomi Aqara Door Sensor



# Playing on mopidy
- platform: template
  sensors:
    nowplaying_mopidy:
      friendly_name: ' '
      value_template: >-
          {%- if is_state("media_player.mopidy", "off") %}
              Off
          {% elif is_state("media_player.mopidy", "paused") %}
              Paused
          {% elif is_state("media_player.mopidy", "playing") %}
              {{ states.media_player.mopidy.attributes.media_title }}
          {% else %}
              Failed
          {%- endif %}
      icon_template: >-
          {%- if is_state("media_player.mopidy", "off") %}
              mdi:stop-circle-outline
          {% elif is_state("media_player.mopidy", "paused") %}
              mdi:pause-circle-outline
          {% elif is_state("media_player.mopidy", "playing") %}
              mdi:play-circle-outline
          {% else %}
              mdi:volume-off
          {%- endif %}

# https://community.home-assistant.io/t/howto-create-battery-alert-without-creating-a-template-for-every-device/30576/6
- platform: template
  sensors:
    low_battery:
      friendly_name: "Low Battery"
      value_template: >
        {%- set threshold = 30 -%}
        {%- set domains = ['light', 'switch', 'sensor'] -%}
        {%- for domain in domains -%}
        {%- for item in states[domain] if ((item.attributes.battery_level is defined and item.attributes['battery_level'] | int < threshold) or ("battery" in item.name | lower and ((item.state | int < threshold and item.state|int != 0) or item.state | lower == "low" or item.state | lower == "unknown"))) -%}
            {{ item.attributes.friendly_name }}{%- if not loop.last %}, {% endif -%}
        {%- endfor -%}
        {%- endfor -%}
        
