- platform: yr
  monitored_conditions:
    - temperature
    - symbol
    - precipitation
    - humidity
    - cloudiness

# Moon
- platform: moon

# Weather
- platform: wunderground
  api_key: !secret wu_api_key
  lang: FR
  monitored_conditions:
    - alerts
    - location
    - temp_c
    - weather
    - feelslike_string
    - precip_1hr_metric
    - wind_kph
# SSL certificate expiration
- platform: cert_expiry
  host: !secret hass_url
  port: !secret ssl_port
# For Alarm Clock
- platform: template
  sensors:
    alarm_time:
      friendly_name: 'Heure'
      value_template: '{{ "%0.02d:%0.02d" | format(states("input_number.alarmhour") | int, states("input_number.alarmminutes") | int) }}'

- platform: time_date
  display_options:
    - 'time'
    - 'date'
    - 'date_time'
    - 'time_date'
    - 'time_utc'
