# based on https://github.com/oakbrad/brad-homeassistant-config/blob/master/config/switches.yaml Switches for MPD
#
- platform: template
  switches:
    mpd_mopidy:
      friendly_name: Musique Mopidy
      value_template: "{{ is_state('media_player.mopidy', 'playing') }}"
      turn_on:
        service: homeassistant.turn_on
        entity_id: media_player.mopidy
      turn_off:
        service: homeassistant.turn_off
        entity_id: media_player.mopidy

- platform: tplink
  host: 192.168.0.30
  name: prise halogene enfants
  enable_leds: True

- platform: tplink
  host: 192.168.0.31
  name: prise salon
  enable_leds: True
