# from https://home-assistant.io/components/binary_sensor.xiaomi_aqara/
# tourne le cube de 90°
- alias: Cube tourner 90 lampe salon
  trigger:
    platform: event
    event_type: xiaomi_aqara.cube_action
    event_data:
      entity_id: binary_sensor.cube_158d00011082c3
      action_type: flip90
  action:
    - service: light.toggle
      entity_id: light.living_lamp

# secouer le cube
- alias: Cube secouer eteindre les lampes
  trigger:
    platform: event
    event_type: xiaomi_aqara.cube_action
    event_data:
      entity_id: binary_sensor.cube_158d00011082c3
      action_type: shake_air
  action:
    - service: light.turn_off
      entity_id: group.lights

# tourne le cube de 180°
- alias: Cube tourner 180 allume veilleuse couloir
  trigger:
    platform: event
    event_type: xiaomi_aqara.cube_action
    event_data:
      entity_id: binary_sensor.cube_158d00011082c3
      action_type: flip180
  condition:
    condition: state
    entity_id: light.gateway_light_7811dcb0612b
    state: 'off'
  action:
    - service: light.turn_on
      entity_id: light.gateway_light_7811dcb0612b
      data:
         brightness: 20
         rgb_color: [255,77,0]

# deplacer le cube
- alias: Cube deplacement eteint couloir
  trigger:
    platform: event
    event_type: xiaomi_aqara.cube_action
    event_data:
      entity_id: binary_sensor.cube_158d00011082c3
      action_type: move
  condition:
    condition: or
    conditions:
      - condition: state
        entity_id: light.gateway_light_7811dcb0612b
        state: 'on'
      - condition: state
        entity_id: light.bedroom_lamp
        state: 'on'
      - condition: state
        entity_id: light.corridor_lamp
        state: 'on'
  action:
    - service: light.turn_off
      entity_id: light.gateway_light_7811dcb0612b
    - service: light.turn_off
      entity_id: light.bedroom_lamp
    - service: light.turn_off
      entity_id: light.corridor_lamp
      #data:
      #  color_name: "gold"

# taper deux fois avec le cube
- alias: Cube taper deux fois allume couloir et chevet
  trigger:
    platform: event
    event_type: xiaomi_aqara.cube_action
    event_data:
      entity_id: binary_sensor.cube_158d00011082c3
      action_type: tap_twice
  action:
    - service: light.turn_off
      entity_id: light.gateway_light_7811dcb0612b
    - service: light.turn_on
      entity_id: light.bedroom_lamp
      data:
         brightness: 20
         rgb_color: [255,77,0]
    - service: light.turn_on
      entity_id: light.corridor_lamp
      data:
         brightness: 20
         rgb_color: [255,77,0]
