# based on https://home-assistant.io/cookbook/dim_lights_when_playing_media/
- alias: "Media player paused/stopped"
  trigger:
    - platform: state
      entity_id: media_player.kodi
      from: 'playing'
      to: 'idle'
  condition:
    - condition: state
      entity_id: sun.sun
      state: 'below_horizon'
  action:
      service: scene.turn_on
      entity_id: scene.nightmode #scene.normal

- alias: "Media player playing"
  trigger:
    - platform: state
      entity_id: media_player.kodi
      to: 'playing'
      from: 'idle'
  condition:
    - condition: state
      entity_id: sun.sun
      state: 'below_horizon'
  action:
      service: scene.turn_on
      entity_id: scene.tvtime
