# https://home-assistant.io/cookbook/turn_on_light_for_10_minutes_when_motion_detected/
# https://home-assistant.io/components/binary_sensor.xiaomi_aqara/
####################
# COULOIR
###################
- alias: mouvement couloir allume lampe journee
  trigger:
    platform: state
    entity_id: binary_sensor.motion_sensor_158d0002254942
    from: 'off'
    to: 'on'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: light.corridor_lamp
        state: 'off'
      - condition: numeric_state
        entity_id: sensor.illumination_158d0002254942
        below: 10
      - condition: state
        entity_id: group.famille
        state: 'home'
      - condition: time
        before: '22:30:00'
  action:
    service: light.turn_on
    entity_id: light.corridor_lamp
#   data:
        #transition: 1
        #brightness: 10
        #rgb_color: [255,153,0]

- alias: mouvement couloir allume lampe soir
  trigger:
    platform: state
    entity_id: binary_sensor.motion_sensor_158d0002254942
    from: 'off'
    to: 'on'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: light.corridor_lamp
        state: 'off'
      - condition: numeric_state
        entity_id: sensor.illumination_158d0002254942
        below: 10
      - condition: state
        entity_id: group.famille
        state: 'home'
      - condition: time
        after: '22:30:01'
  action:
    service: light.turn_on
    entity_id: light.corridor_lamp
#   data:
#        #rgb_color: [255,153,0]
#        #brightness: 5
#        #transition: 1

- alias: mouvement eteint couloir 1 minutes apres
  trigger:
    platform: state
    entity_id: binary_sensor.motion_sensor_158d0002254942
    to: 'off'
    for:
      minutes: 1
  action:
    service: light.turn_off
    entity_id: light.corridor_lamp

####################
# TOILETTES
###################
- alias: mouvement toilettes allume lampe journee
  trigger:
    platform: state
    entity_id: binary_sensor.motion_sensor_158d000276d4e5
    from: 'off'
    to: 'on'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: light.toilet_lamp
        state: 'off'
      - condition: numeric_state
        entity_id: sensor.illumination_158d000276d4e5
        below: 9
      - condition: state
        entity_id: group.famille
        state: 'home'
  action:
    service: light.turn_on
    entity_id: light.toilet_lamp
#   data:
#        transition: 1

- alias: mouvement eteint toilettes 1 minutes apres
  trigger:
    platform: state
    entity_id: binary_sensor.motion_sensor_158d000276d4e5
    to: 'off'
    for:
      minutes: 1
  action:
    service: light.turn_off
    entity_id: light.toilet_lamp

# CAPTEUR VIBRATION - TODO
#- alias: Turn on Living Room Lamp on vibration
#  trigger:
#    platform: event
#    event_type: xiaomi_aqara.movement
#    event_data:
#      entity_id: binary_sensor.vibration_158d0002a222f5
#      movement_type: vibrate
#  action:
#    service: light.toggle
#    data:
#      entity_id: light.corridor_lamp
