# single click aqara wireless switch on gateway light
- alias: "Interrupteur On Chambre simple clic rapide"
  trigger:
    - platform: event
      event_type: click
      event_data:
        entity_id: binary_sensor.switch_158d0001d8e538
        click_type: single
  condition:
    condition: state
    entity_id: light.gateway_light_7811dcb0612b
    state: 'off'
  action:
    - service: light.turn_on
      data_template:
        entity_id: light.gateway_light_7811dcb0612b
        brightness: 40
        rgb_color: [255,77,0]

# single long click aqara wireless swith on two lamps
- alias: "Interrupteur On Chambre simple clic long"
  trigger:
    - platform: event
      event_type: click
      event_data:
        entity_id: binary_sensor.switch_158d0001d8e538
        click_type: long_click_press
  condition:
    condition: state
    entity_id: light.gateway_light_7811dcb0612b
    state: 'off'
  action:
    - service: light.turn_on
      data_template:
        entity_id: light.bedroom_lamp
        brightness: 1
        rgb_color: [255,77,0]
        transition: 3
    - service: light.turn_on
      data_template:
        entity_id: light.gateway_light_7811dcb0612b
        brightness: 40
        rgb_color: [255,77,0]        
        
# single click aqara wireless switch off both lamp
- alias: "Interrupteur Off Chambre simple clic rapide"
  trigger:
    - platform: event
      event_type: click
      event_data:
        entity_id: binary_sensor.switch_158d0001d8e538
        click_type: single
  condition:
    condition: or
    conditions:
      - condition: state
        entity_id: light.gateway_light_7811dcb0612b
        state: 'on'
      - condition: state
        entity_id: light.bedroom_lamp
        state: 'on'
  action:
    - service: light.turn_off
      entity_id: light.gateway_light_7811dcb0612b
    - service: light.turn_off
      entity_id: light.bedroom_lamp

# double click aqara wireless switch off lamps
- alias: "Interrupteur Off des Lampes double clic rapide"
  trigger:
    - platform: event
      event_type: click
      event_data:
        entity_id: binary_sensor.switch_158d0001d8e538
        click_type: double
  action:
    - service: light.turn_off
      entity_id: group.lights

